### PR TITLE
Update srv types

### PR DESCRIPTION
**Pull request by AndyZe**
I don't have a strong opinion about this PR but my thinking is:

- If we just have one service type (`PromptWithImage`) it will be easier to code up the OpenAI server, because it will only need to offer one type of service.

- If the user doesn't want to add an image to the prompt, they can just leave the image field empty.

So I wanted to see what you think.

### CODE REVIEW

**Comment by SteveMacenski** [comment]
I'd think having both would be good.

Also, the response doesn't actually have any ... response string

**Comment by AndyZe** [comment]
That's fine, we can keep both srv types.

Constraining the response to just a `bool` was intentional. If you've ever played with ChatGPT, you know it tends to spit out a bunch of verbose fluff. The correct answer is usually in there but it needs to be parsed out.

But I do think the name of the `srv`s should change to reflect that just a bool is returned. Maybe `Prompt` --> `StringInputBoolResponse`, `PromptWithImage` -> `StringImageInputBoolResponse`

**Comment by yassiezar** [comment]
Hey @AndyZe , 

> If the user doesn't want to add an image to the prompt, they can just leave the image field empty.

I agree with this and think a single srv entry is fine, though the docs will eventually need to clarify this functionality to users. I don't see any logic checking for an image being present in the PR [here](https://github.com/robosoft-ai/ros2_openai_server/pull/1), but I guess that's still in the works.

As an aside, the response is set to `boolean`. To my knowledge, ChatGPT and other LLMs aren't guaranteed to return a yes/no answer, even if prompted to do so. So does that mean the server implementation will be able to somehow translate the LLM's output to some boolean value if a more verbose response is given? Should we consider setting the response to a `string` type and let the user extract the information they want from the AI response?

**Comment by SteveMacenski** [comment]
>  The correct answer is usually in there but it needs to be parsed out.

So... how can you parse it out if there's only a bool? This doesn't seem to generalize. How does the node know what its looking for?

**Comment by AndyZe** [comment]
The OpenAI server does the parsing for yes/no itself and fills in this `bool` response. You can actually play with this functionality already here in this PR. It works!  https://github.com/robosoft-ai/ros2_openai_server/pull/1

Right now I'm thinking the initial use cases will be stuff like:

- Is it safe to move forward?
- Is the door open?
- Did the robot grasp the cube successfully?
- Is there a customer at that table?

All yes/no questions.

**Comment by AndyZe** [comment]
I'll add a generic type with a string response, too  :+1:

**Comment by SteveMacenski** [comment]
Yeah, I think a generic GenAI pass-through option would be nice, not just True/False -- but I can see where applying some `filters` on the results for populating would actually be quite nice. If done with some intentional design,  it would be easy for someone to add their own filters in the future as well

**Comment by AndyZe** [comment]
Look ok now? @yassiezar

**Comment by yassiezar** [comment]
@AndyZe The service names are a bit of a mouthful I think, but the rest looks fine to me

**Comment by AndyZe** [comment]
can you suggest something else? I'm trying to convey what the inputs and outputs are, but I completely agree

**Comment by AndyZe** [comment]
Shortened to `BoolResponse.srv` and `StringResponse.srv`

**Comment by AndyZe** [comment]
@yassiezar per our conversation, i consolidated to just one srv type and added an `is_valid` response field.

Eventually we'll need more srv types, for example if somebody wants to send a voice prompt. But I think this should be fine for now.

**Comment by AndyZe** [comment]
Any last words of wisdom before merging?

**Review by brettpac — APPROVED** [review]
I think we're good to go here. Especially for a first shot.
I like what you guys did with simplifying and renaming to make the input obvious.

**Pull request merged**
